version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  postgres_data:

networks:
  postgres_net:
    name: postgres_net